@tool
extends RefCounted
class_name SteamGameCodeGenerator

## Generates a type-safe GDScript facade (SteamGame.gd) from the Steamworks
## settings (see SteamSettingsIO) — the Godot equivalent of Unity's
## SteamToolsCodeGenerator producing SteamTools.Game. Scope matches Unity's own
## Foundation-level generator exactly: Achievements/Stats/Leaderboards only, no
## DLC/Input (those are Toolkit-only additions in Unity too, and are explicitly
## deferred here — see the design plan).
##
## Generated shape (dev-facing call site):
##   SteamGame.Achievements.ACH_WIN_ONE_GAME.Unlock()
##   SteamGame.Stats.NumWins.SetIntValue(...)
## Each nested "class Achievements/Stats/Leaderboards" holds one
## "static var <ident> := XxxData.Get(api_name)" per configured entry —
## AchievementData/StatData/LeaderboardData are GDExtension-bound RefCounted
## types whose .new() only supports zero arguments (confirmed the hard way —
## an earlier version of this generator emitted XxxData.new(api_name) and it
## failed to parse at all), so construction goes through their real bound
## static factory (Get(apiName)) instead. GDScript's static var CAN be
## initialized with an arbitrary expression/call (evaluated once at
## script-load, confirmed empirically), so this is still real field access
## checked by Godot's own parser, not a runtime string lookup: a typo'd
## identifier at the call site is a parse error, the same guarantee Unity's
## compiled C# static class gave.
##
## SteamGame.gd also generates a static Initialise(parent, ...) method that
## does ALL the actual Steam init work itself — creating and configuring the
## real SteamApi engine wrapper as a child of 'parent' — matching Unity's
## generated SteamTools.Game.Initialise(). Alongside it, generate() also writes
## a tiny bootstrap Node script (SteamGameLoader.gd, next to SteamGame.gd) whose
## entire job is calling that Initialise() from _ready() — this is what
## actually becomes the autoload (see SteamAutoloadSetup), instead of the
## native SteamApi class itself being the autoload root. SteamApi is NOT
## redundant (its _process() is what pumps SteamAPI_RunCallbacks() every
## frame, which genuinely needs a live tree node) — it just becomes an
## implementation detail the generated code owns and creates at runtime,
## rather than something a dev has to see/configure directly in the Autoload
## list. The human-facing config Unity exposed (Auto Initialise/Auto Logon/
## Debug) lives as @export fields on the generated SteamGameLoader.gd node
## instead, editable directly on the autoload node in the Inspector.

## First line of every generated file — how _find_existing_script() recognizes
## "this is OUR generated file" wherever the dev has moved it to, mirroring
## Unity's marker-comment scan (AssetDatabase.FindAssets + text search) rather
## than trusting a fixed path or a stored preference.
const MARKER := "# Auto-generated by SteamGameCodeGenerator — do not edit by hand."
const HASH_PREFIX := "# steamtools-hash:"

## Only used the FIRST time, when no existing generated file is found anywhere
## in the project — mirrors Unity's default Assets/Scripts/Generated/SteamTools.Game.cs.
const DEFAULT_PATH := "res://Scripts/Generated/SteamGame.gd"

## Not exhaustive of every future GDScript keyword, but covers the reserved
## words that would actually collide with a plausible Achievement/Stat/
## Leaderboard API name. GDScript has no C#-style "@identifier" escape, so a
## collision gets a trailing underscore instead.
const GDSCRIPT_RESERVED_WORDS := [
	"if", "elif", "else", "for", "while", "match", "when", "break", "continue", "pass", "return",
	"class", "class_name", "extends", "is", "in", "as", "self", "signal", "func", "static", "const",
	"enum", "var", "await", "breakpoint", "tool", "and", "or", "not", "true", "false", "null",
	"void", "super", "preload", "assert", "yield", "namespace", "trait", "PI", "TAU", "INF", "NAN",
]

## Filename of the bootstrap Node script generated alongside SteamGame.gd —
## not marker-searched/relocatable like SteamGame.gd itself (its content never
## varies with settings, so there's nothing to preserve across regeneration);
## always written next to wherever SteamGame.gd actually lives.
const LOADER_FILENAME := "SteamGameLoader.gd"

## Regenerates the generated file (creating it at DEFAULT_PATH if none exists
## yet anywhere in the project) from 'settings' — see SteamSettingsIO's schema.
## Returns the directory SteamGame.gd (and SteamGameLoader.gd) were written
## to, so callers (see SteamAutoloadSetup) know where the loader script ended
## up without having to re-derive it.
static func generate(settings: Dictionary) -> String:
	var body := _build_body(settings)
	var full_text := "%s\n%s%s\n%s" % [MARKER, HASH_PREFIX, body.sha256_text(), body]

	var path := _find_existing_script()
	if path.is_empty():
		path = DEFAULT_PATH
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))

	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_warning("SteamGameCodeGenerator: failed to write %s" % path)
		return path.get_base_dir()

	file.store_string(full_text)
	file = null # close before writing the sibling file below

	var loader_path := path.get_base_dir().path_join(LOADER_FILENAME)
	var loader_file := FileAccess.open(loader_path, FileAccess.WRITE)
	if loader_file == null:
		push_warning("SteamGameCodeGenerator: failed to write %s" % loader_path)
	else:
		loader_file.store_string(_build_loader_body())

	return path.get_base_dir()

## Cheap (no write, no recompute of file location beyond the same marker scan)
## — safe to poll from the dock's staleness label on every settings change.
static func is_stale(settings: Dictionary) -> bool:
	var path := _find_existing_script()
	if path.is_empty():
		return true
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return true
	var text := file.get_as_text()
	var first_nl := text.find("\n")
	if first_nl == -1:
		return true
	var second_nl := text.find("\n", first_nl + 1)
	if second_nl == -1:
		return true
	if text.substr(0, first_nl) != MARKER:
		return true
	var hash_line := text.substr(first_nl + 1, second_nl - first_nl - 1)
	if not hash_line.begins_with(HASH_PREFIX):
		return true
	var stored_hash := hash_line.substr(HASH_PREFIX.length())
	return stored_hash != _build_body(settings).sha256_text()

## Recursively searches res:// (skipping addons/ and any hidden/dot directory —
## .godot, .git, etc.) for a .gd file whose first line is MARKER. Returns "" if
## none found. A marker-comment scan, not a stored path or reflection lookup —
## same approach as Unity's, and what lets a dev freely relocate the generated
## file without breaking regeneration.
static func _find_existing_script(root: String = "res://") -> String:
	var dir := DirAccess.open(root)
	if dir == null:
		return ""
	dir.list_dir_begin()
	var entry := dir.get_next()
	while entry != "":
		if entry == "." or entry == "..":
			entry = dir.get_next()
			continue
		var full := root.path_join(entry)
		if dir.current_is_dir():
			if entry != "addons" and not entry.begins_with("."):
				var found := _find_existing_script(full)
				if not found.is_empty():
					return found
		elif entry.ends_with(".gd"):
			var file := FileAccess.open(full, FileAccess.READ)
			if file != null and file.get_line() == MARKER:
				return full
		entry = dir.get_next()
	dir.list_dir_end()
	return ""

static func _build_body(settings: Dictionary) -> String:
	var lines := PackedStringArray()
	lines.append("extends RefCounted")
	lines.append("class_name SteamGame")
	lines.append("")
	lines.append("const AppId := %d" % int(settings.get("app_id", 0)))
	lines.append("")
	lines.append("## Creates and configures the real SteamApi engine wrapper as a child of")
	lines.append("## 'parent', then initialises it — the only place SteamApi itself is ever")
	lines.append("## touched directly. autoInitialise is always forced off on the created")
	lines.append("## instance regardless of the 'auto_initialise' param below: that native")
	lines.append("## property only matters for SteamApi's OWN _ready(), and we always drive")
	lines.append("## init explicitly ourselves right here instead, to avoid any ambiguity")
	lines.append("## about whether it already ran automatically before we got to it.")
	lines.append("##")
	lines.append("## Gated on the Subsystems tab's own Start Mode setting FIRST, before any")
	lines.append("## SteamApi node is even created — matching SteamToolsCodeGenerator's")
	lines.append("## AppendInitialise on the Unity side. Without this check, Disabled never")
	lines.append("## actually stopped SteamAPI_Init(): it only stopped SteamworksSubsystem's")
	lines.append("## own callback pump (since a Disabled subsystem is dropped from")
	lines.append("## SubsystemManager::boot() before it's ever ticked), leaving Steam")
	lines.append("## fully initialised with its callback queue permanently starved — worse")
	lines.append("## than either \"on\" or \"off\". OnDemand and Automatic are intentionally")
	lines.append("## treated the same here (both initialise immediately): SteamworksSubsystem")
	lines.append("## never overrides initialize(), so there is no deferred-init hook for")
	lines.append("## OnDemand to plug into yet — only Disabled has real, distinct behavior.")
	lines.append("static func Initialise(parent: Node, auto_initialise: bool = true, auto_logon: bool = true, debug: bool = false) -> void:")
	lines.append("\tif int(ProjectSettings.get_setting(\"steamworks/start_mode\", 2)) == 0:")
	lines.append("\t\tprint(\"[SteamGame] Steamworks disabled in Subsystems settings; not initialising.\")")
	lines.append("\t\treturn")
	lines.append("\tvar api: Node = ClassDB.instantiate(\"SteamApi\")")
	lines.append("\tapi.call(\"set_autoInitialise\", false)")
	lines.append("\tapi.call(\"set_autoLogOn\", auto_logon)")
	lines.append("\tapi.call(\"set_debug\", debug)")
	lines.append("\tparent.add_child(api)")
	lines.append("\tif AppId > 0:")
	lines.append("\t\tapi.call(\"set_appId\", AppId)")
	lines.append("\tif auto_initialise:")
	lines.append("\t\tapi.call(\"InitialiseClient\")")

	var achievements: Array = settings.get("achievements", []).duplicate()
	achievements.sort()
	if not achievements.is_empty():
		lines.append("")
		lines.append("class Achievements:")
		var seen := {}
		var map_entries := PackedStringArray()
		for api_name in achievements:
			var ident := _unique_identifier(str(api_name), seen)
			lines.append("\tstatic var %s: AchievementData = AchievementData.Get(\"%s\")" % [ident, api_name])
			map_entries.append("\"%s\": %s" % [api_name, ident])
		lines.append("\tstatic func get_all() -> Dictionary:")
		lines.append("\t\treturn {%s}" % ", ".join(map_entries))

	var stats: Array = settings.get("stats", []).duplicate()
	stats.sort()
	if not stats.is_empty():
		lines.append("")
		lines.append("class Stats:")
		var seen2 := {}
		var map_entries2 := PackedStringArray()
		for api_name in stats:
			var ident := _unique_identifier(str(api_name), seen2)
			lines.append("\tstatic var %s: StatData = StatData.Get(\"%s\")" % [ident, api_name])
			map_entries2.append("\"%s\": %s" % [api_name, ident])
		lines.append("\tstatic func get_all() -> Dictionary:")
		lines.append("\t\treturn {%s}" % ", ".join(map_entries2))

	var leaderboards: Array = settings.get("leaderboards", []).duplicate()
	leaderboards.sort_custom(func(a, b): return str(a.get("name", "")) < str(b.get("name", "")))
	if not leaderboards.is_empty():
		lines.append("")
		lines.append("class Leaderboards:")
		var seen3 := {}
		var map_entries3 := PackedStringArray()
		for lb in leaderboards:
			var api_name: String = str(lb.get("name", ""))
			var ident := _unique_identifier(api_name, seen3)
			lines.append("\tstatic var %s: LeaderboardData = LeaderboardData.Get(\"%s\")" % [ident, api_name])
			map_entries3.append("\"%s\": %s" % [api_name, ident])
		lines.append("\tstatic func get_all() -> Dictionary:")
		lines.append("\t\treturn {%s}" % ", ".join(map_entries3))

	return "\n".join(lines) + "\n"

## The bootstrap Node script that actually becomes the autoload (see
## SteamAutoloadSetup) — deliberately tiny and hardcoded to just call
## SteamGame.Initialise(), passing through its own @export fields as the
## human-facing config a dev can tweak directly on the autoload node in the
## Inspector, without needing to know SteamApi (the native class) exists at
## all. Content never depends on settings, so it's always rewritten in full
## rather than marker/hash-tracked like SteamGame.gd itself.
static func _build_loader_body() -> String:
	var lines := PackedStringArray()
	lines.append("# Auto-generated by SteamGameCodeGenerator alongside SteamGame.gd.")
	lines.append("extends Node")
	lines.append("")
	lines.append("@export var auto_initialise: bool = true")
	lines.append("@export var auto_logon: bool = true")
	lines.append("@export var debug: bool = false")
	lines.append("")
	lines.append("func _ready() -> void:")
	lines.append("\tSteamGame.Initialise(self, auto_initialise, auto_logon, debug)")
	return "\n".join(lines) + "\n"

## Turns an arbitrary Steam API name into a valid, unique-within-this-section
## GDScript identifier — strips invalid characters, collapses repeats, prefixes
## a leading digit, suffixes a reserved-word collision, and (not present in
## Unity's version, added here since two API names can sanitize to the same
## identifier even when the raw names are already unique) numbers a collision
## against an already-used identifier in the same 'seen' set rather than
## silently emitting two fields with the same name, which would be a GDScript
## parse error.
static func _unique_identifier(raw: String, seen: Dictionary) -> String:
	var base := _sanitize_identifier(raw)
	var ident := base
	var suffix := 2
	while seen.has(ident):
		ident = "%s_%d" % [base, suffix]
		suffix += 1
	seen[ident] = true
	return ident

static func _sanitize_identifier(raw: String) -> String:
	var result := ""
	for i in raw.length():
		var c := raw[i]
		if c == "_" or (c >= "a" and c <= "z") or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9"):
			result += c
		else:
			result += "_"
	while result.contains("__"):
		result = result.replace("__", "_")
	result = result.trim_prefix("_").trim_suffix("_")
	if result.is_empty():
		return "_%s" % str(raw.hash())
	if result[0] >= "0" and result[0] <= "9":
		result = "_" + result
	if GDSCRIPT_RESERVED_WORDS.has(result):
		result += "_"
	return result
